// GET HOME DETAILS

export const GET_HOME_DETAILS_REQUEST = "GET_HOME_DETAILS_REQUEST"
export const GET_HOME_DETAILS_SUCCESS = "GET_HOME_DETAILS_SUCCESS"
export const GET_HOME_DETAILS_FAIL = "GET_HOME_DETAILS_FAIL"

//GET SERVICES

export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST"
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS"
export const GET_SERVICES_FAIL = "GET_SERVICES_FAIL"


//GET SKILLS

export const GET_SKILLS_REQUEST = "GET_SKILLS_REQUEST"
export const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS"
export const GET_SKILLS_FAIL = "GET_SKILLS_FAIL"

//GET PORTFOLIO

export const GET_PORTFOLIO_REQUEST = "GET_PORTFOLIO_REQUEST"
export const GET_PORTFOLIO_SUCCESS = "GET_PORTFOLIO_SUCCESS"
export const GET_PORTFOLIO_FAIL = "GET_PORTFOLIO_FAIL"

//GET TESTMONIAL

export const GET_TESTMONIAL_REQUEST = "GET_TESTMONIAL_REQUEST"
export const GET_TESTMONIAL_SUCCESS = "GET_TESTMONIAL_SUCCESS"
export const GET_TESTMONIAL_FAIL = "GET_TESTMONIAL_FAIL"